<?php View::flash(); ?>

<div class="container shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <div class="container-overflow">

        <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
            <thead>
                <tr>
                    <th>NUM</th>
                    <th class="col-hidden" data-search="login" data-order="login">LOGIN</th>
                    <th class="col-hidden" data-search="nombre" data-order="nombre">NOMBRE</th>
                    <th class="col-hidden" data-search="apellido" data-order="apellido">APELLIDO</th>
                    <th class="col-hidden" data-search="email" data-order="email">EMAIL</th>                                        
                    <th class="col-hidden" data-order="estado_usuario">ESTADO</th>
                    <th class="col-blocked text-center">ACCIONES</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($usuarios->items as $usuario): ?>
                    <?php $key_shw = Security::setKey($usuario->id, 'upload_reports'); ?>
                    <tr>
                        <td><?php echo $usuarios->counter; ?></td>
                        <td><?php echo $usuario->login; ?></td>
                        <td><?php echo $usuario->nombre; ?></td>
                        <td><?php echo $usuario->apellido; ?></td>
                        <td><?php echo $usuario->email; ?></td>
                        <td><?php echo ($usuario->estado_usuario == EstadoUsuario::ACTIVO) ? '<span class="label label-success" title="'.$usuario->descripcion.'" rel="tooltip">Activo</span>' : '<span class="label label-danger" title="'.$usuario->descripcion.'" rel="tooltip">Bloqueado</span>'; ; ?></td>
                        <td>
                            <?php echo DwHtml::buttonTable('Subir Reporte', "calendario/upload/reports/$key_shw/", NULL, 'info', 'fa-upload'); ?>                            
                        </td>
                    </tr>
                    <?php $usuarios->counter++; ?>
                <?php endforeach; ?>
            </tbody>
        </table>

    </div>

    <?php View::partial('paginators/default', false, array('page'=>$usuarios, 'url'=>"sistema/usuarios/listar/$order/")); ?>

</div>