<html>
<head>
	<title>Calendario</title>    
    <?php Tag::css('bee/fullcalendar'); ?>
    <?php Tag::css('bee/style'); ?>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    
    <?php Tag::css('bee/font-awesome.min'); ?>
    <?php Tag::css('bee/DateTimePicker.min'); ?>
    <?php echo Html::includeCss(); ?>       
</head>
<body>
	<header>
		<div id="menu"></div>
		<div id="logout"><?php echo DwHtml::link('sistema/login/salir', '[ Log Out ]'); ?></div>
	</header>
	<article id="panels">
		<div id="usuario">[ <?php echo Session::get('nombre');?> ]</div>
		<div id="logoCliente">
			<?php echo DwHtml::img("upload/personas/" . Session::get('fotografia'), Session::get('nombre') . ' ' . Session::get('apellido')); ?>
		</div>
		<div id="paneles">
			<div class="tab" id="progress">
				<input id="radio1" type="radio" name="acordeon" value="progress"/>
				<label for="radio1">Progress Report<i class="fa fa-download"></i><i class="fa fa-filter"></i></label>
				<div class="contenido">
					<ul>
						<?php foreach ($progress_report as $key => $value): ?>
							<?php $key_dwn = Security::setKey($value->id, 'descargar_reporte'); ?>
							<?php $dwn = DwHtml::buttonTable('Descargar Reporte', "calendario/upload/descargar/$key_dwn/", array('class'=>'no-ajax', 'target'=>'_self'), 'info', 'fa-download'); ?>
							<li><span><?php echo $value->fecha?></span><span><?php echo $dwn?></span></li>
						<?php endforeach; ?>
					</ul>
				</div>
			</div>


			<div class="tab" id="demographics">
				<input id="radio2" type="radio" name="acordeon" value="demographics"/>
				<label for="radio2">Demographics<i class="fa fa-download"></i><i class="fa fa-filter"></i></label>
				<div class="contenido">
					<ul>
						<?php foreach ($demographics_report as $key => $value): ?>
							<?php $key_dwn = Security::setKey($value->id, 'descargar_reporte'); ?>
							<?php $dwn = DwHtml::buttonTable('Descargar Reporte', "calendario/upload/descargar/$key_dwn/", array('class'=>'no-ajax', 'target'=>'_self'), 'info', 'fa-download'); ?>
							<li><span><?php echo $value->fecha?></span><span><?php echo $dwn?></span></li>
						<?php endforeach; ?>
					</ul>
				</div>
			</div>
			<div class="tab" id="ideas">
				<input id="radio3" type="radio" name="acordeon" value="beehive"/>
				<label for="radio3">Beehive of Ideas<i class="fa fa-download"></i><i class="fa fa-filter"></i></label>
				<div class="contenido">
					<ul>
						<?php foreach ($beehive_report as $key => $value): ?>
							<?php $key_dwn = Security::setKey($value->id, 'descargar_reporte'); ?>
							<?php $dwn = DwHtml::buttonTable('Descargar Reporte', "calendario/upload/descargar/$key_dwn/", array('class'=>'no-ajax', 'target'=>'_self'), 'info', 'fa-download'); ?>
							<li><span><?php echo $value->fecha?></span><span><?php echo $dwn?></span></li>
						<?php endforeach; ?>
					</ul>
				</div>
			</div>
			<div class="tab" id="account">
				<input id="radio4" type="radio" name="acordeon" value="account"/>
				<label for="radio4">Account Info</label>
				<div class="contenido">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore e</div>
			</div>
			<div class="tab" id="winner">
				<input id="radio5" type="radio" name="acordeon" value="contest"/>
				<label  for="radio5">Contest Picker</label>
				<div class="contenido winner" >
					<textarea class="texto"></textarea>
					<div id="winnerName"></div>
					<button id="WinnerButton">Pick Winner</button>
				</div>
			</div>
		</div>
	</article>
	<article id="calendario">
		<div id="contenedor">
			<div id="calendar"></div>
			<div id="agregar">
				<div id="capa"></div>
				<div id="taskCont">
					<h2>NEW TASK</h2>
					<div id="redes">
						<ul>
							<li><i class="fa fa-facebook" id="facebook"></i></li>
							<li><i class="fa fa-twitter" id="twitter"></i></li>
							<li><i class="fa fa-instagram" id="instagram"></i></li>
							<li><i class="fa fa-linkedin" id="linkedin"></i></li>
							<li><i class="fa fa-pinterest" id="pinterest"></i></li>
							<li><i class="fa fa-youtube" id="youtube"></i></li>
							<li><i class="fa fa-google-plus" id="plus"></i></li>
						</ul>
					</div>
					<div id="imaEvent"></div>
					<div id="taskText"><textarea type="text" value="add task"></textarea></div>
					<div id="taskDescription"><textarea type="text" value="add task"></textarea></div>
					<div id="taskAuthor"><textarea type="text" value="add task"></textarea></div>
					<!--date-->
					<div class="input-group bootstrap-timepicker timepicker">
			            <input id="timepicker1" type="text" class="form-control input-small">
			            <span class="input-group-addon"><i class="fa fa-calendar-o"></i></span>
			        </div>
					<!--date-->
					<div id="buttons">
						<div class="taskButton" id="upload" style="float:left;"><i class="fa fa-upload"></i>   upload file</div>
						<div class="taskButton" id="discard" style="float:right;">discard</div>
						<div class="taskButton" id="save" style="float:right;">save</div>
					</div>
					<div id="uploadModule">
						<form enctype="multipart/form-data" class="formulario">
					        <input name="archivo" type="file" id="imagen" /><br /><br />
					        <input type="button" value="Upload File" /><br />
					    </form>
					    <!--div para visualizar mensajes-->
					    <div class="messages"></div>
					</div>
				</div>
				
				
			</div>
		</div>
	</article>

	<script type="text/javascript">
		PUBLIC_PATH = '<?php echo PUBLIC_PATH; ?>';
		var Eventos = <?php echo json_encode($eventos)?>;
	</script>

    <?php echo Tag::js('bee/jquery.min'); ?>
    <?php echo Tag::js('bee/moment.min'); ?>
    <?php echo Tag::js('bee/fullcalendar'); ?>
    <?php echo Tag::js('bee/bootstrap-timepicker'); ?>
    <?php echo Tag::js('html5shiv'); ?>    
	<?php echo Tag::js('backend'); ?>
    <?php echo Tag::js('bee/bee'); ?>
    <?php echo Tag::js('bee/jspdf.min'); ?>
    <?php echo Tag::js('bee/jquery.tabletojson'); ?>
    <?php echo Tag::js('bee/jspdf.plugin.cell'); ?>
</body>
</html>

