<?php View::flash(); ?>

<div class="container shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open(); ?>

        <div class="row">
            <div class="col-md-4">
                <?php echo DwForm::text('empresa.nombre', array('class'=>'input-lower'), NULL, 'Nombre'); ?>
            </div>
        </div>

        <div class="row">
            <div class="form-actions">
                <?php echo DwForm::send('Guardar empresa'); ?>
                <?php echo DwForm::cancel(); ?>
                <?php echo DwForm::focus('empresa-nombre'); ?>
            </div>
        </div>

    <?php echo DwForm::close(); ?>

</div>
