<?php View::flash(); ?>

<script type="text/javascript">
    $(function() {
        $('table').kgrid({       
            order_attr      : '<?php echo (APP_AJAX) ? 'class="js-link js-spinner"' : ''; ?>',
            order_to        : $.KumbiaPHP.publicPath+'calendario/empresa/listar/'
        });
    });
</script>

<div class="container shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <div class="btn-toolbar btn-toolbar-top">
        <div class="row">
            <div class="btn-actions">
                <?php echo DwHtml::button("calendario/empresa/agregar/", 'agregar', NULL, 'fa-check-square-o', APP_AJAX); ?>
            </div>            
        </div>
    </div>

    <div class="container-overflow">

        <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
            <thead>
                <tr>
                    <th>NUM</th>
                    <th class="col-hidden" data-order="nombre">NOMBRE</th>
                    <th class="col-blocked text-center">ACCIONES</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($empresas->items as $empresa): ?>
                    <?php $key_shw = Security::setKey($empresa->id, 'shw_empresa'); ?>
                    <?php $key_del = Security::setKey($empresa->id, 'eliminar_empresa'); ?>
                    <tr>
                        <td><?php echo $empresas->counter; ?></td>
                        <td><?php echo $empresa->nombre; ?></td>
                        <td><?php echo $empresa->creado_at; ?></td>
                        <td>
                            <?php echo DwHtml::buttonTable('Ver Empresa', "calendario/empresa/ver/$key_shw/", NULL, 'info', 'fa-search'); ?>                            
                            <?php echo DwHtml::buttonTable('Eliminar Empresa', "calendario/empresa/eliminar/$key_del/", NULL, 'success', 'fa-flag'); ?>
                        </td>
                    </tr>
                    <?php $empresas->counter++; ?>
                <?php endforeach; ?>
            </tbody>
        </table>

    </div>

    <?php View::partial('paginators/default', false, array('page'=>$empresas, 'url'=>"calendario/empresa/listar/$order/")); ?>

</div>